name: 'Distribute'
description: 'Distributes an application to Firebase App Distribution'

inputs:
  serviceCredentials:
    description: 'Content of Service Credentials private key JSON file'
    required: true
  path:
    description: 'The path to the file'
    required: true
  application:
    description: 'The application ID'
    required: true
  groups:
    description: 'The list of distribution groups'
    required: true

runs:
  using: 'composite'

  steps:
    # Extracts latest release notes from CHANGELOG.md.
    - name: Prepare release notes
      shell: bash
      run: ./scripts/last_changelog_section.sh CHANGELOG.md > RELEASE_NOTES.md

    # Creates a new distribution with release notes created before.
    - name: Upload a file to Firebase App Distribution
      uses: wzieba/Firebase-Distribution-Github-Action@v1
      with:
        appId: ${{ inputs.application }}
        serviceCredentialsFileContent: ${{ inputs.serviceCredentials }}
        groups: ${{ inputs.groups }}
        file: ${{ inputs.path }}
        releaseNotesFile: RELEASE_NOTES.md
