// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_stage.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyU8qokxKyqL8UbUFdOMek0cbcWtsRXCg',
    appId: '1:806560021540:web:9be29b3e13dced8ad82cb1',
    messagingSenderId: '806560021540',
    projectId: 'zachran-obed-dev',
    authDomain: 'zachran-obed-dev.firebaseapp.com',
    storageBucket: 'zachran-obed-dev.appspot.com',
    measurementId: 'G-PQW74YT6NV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5087u0aPHCv7B4t-W-9tYEbD200yRw5M',
    appId: '1:806560021540:android:3b1f0e9c880ecc7ed82cb1',
    messagingSenderId: '806560021540',
    projectId: 'zachran-obed-dev',
    storageBucket: 'zachran-obed-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwlhJBakcOeSJPK0d8GnEwFAuw_JKopuQ',
    appId: '1:806560021540:ios:974c2091a6d029c1d82cb1',
    messagingSenderId: '806560021540',
    projectId: 'zachran-obed-dev',
    storageBucket: 'zachran-obed-dev.appspot.com',
    iosBundleId: 'cz.etnetera.mobile.zachranobed.test',
  );
}
