// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_prod.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBB3pFlAaQ7stPaoaICgYYrjspFnbov6OA',
    appId: '1:925797833830:web:c8f63160861cf75c8c21a7',
    messagingSenderId: '925797833830',
    projectId: 'zachran-obed',
    authDomain: 'zachran-obed.firebaseapp.com',
    storageBucket: 'zachran-obed.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDV8g0z-EBnGPEzKISr3D1UO1XJyoGvIa0',
    appId: '1:925797833830:android:c2fe4064acaf46468c21a7',
    messagingSenderId: '925797833830',
    projectId: 'zachran-obed',
    storageBucket: 'zachran-obed.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYkCjaySfTEdIIaDMPbFikbA7Z1BZonVQ',
    appId: '1:925797833830:ios:d2af9b959bdf16748c21a7',
    messagingSenderId: '925797833830',
    projectId: 'zachran-obed',
    storageBucket: 'zachran-obed.appspot.com',
    iosClientId: '925797833830-m7l33ahoa5a8fctmg1bfvqqo9nf8k7fq.apps.googleusercontent.com',
    iosBundleId: 'cz.zachranobed',
  );
}
