name: 'Sets Up Environment'
description: 'Sets up Java, Flutter and correct version code before build'

runs:
  using: 'composite'

  steps:
    # Sets up Java environment.
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    # Sets up Flutter environment.
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: 3.22.1

    # Installs Flutter dependencies.
    - name: Install dependencies
      shell: bash
      run: flutter pub get

    # Updates a version code in pubspec.yaml based on count of commits in current branch.
    - name: Update version code
      shell: bash
      run: ./scripts/update_version_code.sh
