# This workflow is designed to automate the process of building a release APK for the 'stage' flavor
# of a Flutter application and distributing it to AppCenter.
name: Build Stage

on:
  # Workflow is triggered manually through the GitHub Actions interface.
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      # Checkouts the repository with entire commit history, which is needed to calculate the
      # correct build version code in 'Setup environment' step.
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Setups Java, Flutter and correct version code before build.
      - name: Setup environment
        uses: ./.github/actions/setup

      # Builds a release APK for the 'stage' flavor.
      - name: Build Android APK
        run: flutter build apk --release --flavor stage

      # Uploads Android related artifacts (APK and mappings) from build to GitHub Actions.
      - name: Upload artifacts
        uses: ./.github/actions/artifacts-android

      # Upload APK to the AppCenter slot and distribute it with latest release notes.
      - name: Distribute to AppCenter
        uses: ./.github/actions/distribute
        with:
          token: ${{ secrets.APPCENTER_TOKEN }}
          path: 'build/app/outputs/flutter-apk/app-stage-release.apk'
          application: ${{ secrets.APPCENTER_ANDROID_STAGE_APP_NAME }}
          groups: ${{ vars.APPCENTER_GROUPS }}
