name: Build Web Dev

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
#      # Checkouts the repository with entire commit history, which is needed to calculate the
#      # correct build version code in 'Setup environment' step.
#      - name: Checkout repository
#        uses: actions/checkout@v4
#        with:
#          fetch-depth: 0
#
#      # Setups Java, Flutter and correct version code before build.
#      - name: Setup environment
#        uses: ./.github/actions/setup
#
#      - name: Build web
#        run: flutter build web --release --no-tree-shake-icons --base-href "/zachranobed-web-dev/" --dart-define=FLUTTER_APP_FLAVOR=dev

      - name: Checkout web repository
        uses: actions/checkout@v4
        with:
          repository: 'zachran-jidlo/zachranobed-web-dev'
          token: ${{ secrets.WEB_GITHUB_TOKEN }}
          path: destination

      - name: Copy files to destination repository
        run: |
          cd destination
          git rm *
          echo "test" > test.txt
          git config user.name "ZachranJidlo Bot"
          git config user.email "zachran-jidlo-bot@users.noreply.github.com"
          git add .
          git commit -m "Deploy new version"
          git push origin main