name: Scheduled Firestore Modification

on:
  schedule:
    - cron: '*/5 * * * *'  # This runs the script every hour at the start of the hour

jobs:
  modify-firestore:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        ref: feature/ZOB-201_delivery_report_script #develop  # Ensure it checks out the develop branch

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # Specify the Node.js version you need

    - name: Install dependencies
      run: |
        cd ./cron/scripts
        npm install

    - name: Run Firestore modification script
      run: node cron/scripts/create-delivery-report.js
      env:
        FIREBASE_API_KEY: "AIzaSyCyU8qokxKyqL8UbUFdOMek0cbcWtsRXCg"
        FIREBASE_AUTH_DOMAIN: "zachran-obed-dev.firebaseapp.com"
        FIREBASE_PROJECT_ID: "zachran-obed-dev"
        FIREBASE_STORAGE_BUCKET: "zachran-obed-dev.appspot.com"
        FIREBASE_MESSAGING_SENDER_ID: "806560021540"
        FIREBASE_APP_ID: "1:806560021540:web:9be29b3e13dced8ad82cb1"
